config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from tesserae.apps.base_portal.auth import login_request
from tesserae.apps.base_portal.views.custom import ProfileRedirectView, CustomLogoutView, CustomEmailLoginView

from allauth.socialaccount.views import SignupView
from allauth.socialaccount.providers.google.views import oauth2_login, oauth2_callback

from tesserae.apps.base_portal.views.dashboard import StaffDashboardView, ParticipantDashboardView

from tesserae.apps.base_portal.views.landing import LandingView

urlpatterns = [
      # url(r'^login/', login_request, name='login'),
      url(r'^$', LandingView.as_view(), name='home'),

      # url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

      # Django Admin, use {% url 'admin:index' %}
      url(settings.ADMIN_URL, admin.site.urls),

      # User management
      # url(r'^users/', include('tesserae.apps.users.urls', namespace='users')),
      # url(r'^accounts/', include('allauth.urls')),

      # Redirect from /accounts/profile/ to the home page.
      url(r'^accounts/profile/', ProfileRedirectView.as_view()),
      url(r'^accounts/logout/', CustomLogoutView.as_view()),

      url(r'^accounts/login/', CustomEmailLoginView.as_view()),

      # url(r'^accounts/google/login/', oauth2_login),
      # url(r'^accounts/google/login/callback/', oauth2_callback),

      # Include allauth urls.
      url(r'^accounts/', include('allauth.urls')),

      # Your stuff: custom urls includes go here
      url(r'^portal/', include('tesserae.apps.urls', namespace='portal')),
]
  # ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tesserae/apps/issue_app/urls.py
from django.conf.urls import url

from tesserae.apps.issue_app.views import IssueCreate, MyIssueList, AllIssuesList, IssueUpdate, MyIssueDetail, \
    add_note_view, get_notes_list_view, AssignedIssueList, close_issue, open_issue

urlpatterns = [
    url(r'^create$', IssueCreate.as_view(), name='new_issue'),
    url(r'^my-issues$', MyIssueList.as_view(), name='my_issues_list'),
    url(r'^list$', AllIssuesList.as_view(), name='all_issues_list'),
    url(r'^my-assigned-issues$', AssignedIssueList.as_view(), name='admin_assigned_issues'),
    url(r'^update/(?P<pk>\d+)$', IssueUpdate.as_view(), name='admin_issues_update'),
    url(r'^detail/(?P<pk>\d+)$', MyIssueDetail.as_view(), name='issue_details'),
    url(r'^submit-note$', add_note_view, name='submit_note'),
    url(r'^get-note-list$', get_notes_list_view, name='get_note_list'),
    url(r'^close_issue$', close_issue, name='close_issue'),
    url(r'^open_issue$', open_issue, name='open_issue')
]

tesserae/apps/urls.py
from django.conf.urls import include, url

from tesserae.apps.base_portal.views.dashboard import StaffDashboardView, ParticipantDashboardView, \
    avg_stream_compliance_chart_ajax, overall_compliance_chart_ajax, stream_compliance_chart_ajax, \
    participant_filter_issues_ajax, staff_filter_issues_ajax, staff_filter__unassigned_issues_ajax, \
    get_average_compliance_data, get_overall_compliance, get_stream_compliance

urlpatterns = [
    url(r'^staff/', include('tesserae.apps.staff_app.urls', namespace='staff')),

    # Ajax calls for changing charts on staff dashboard
    url(r'^staff-dashboard/avg-stream-compliance-chart', avg_stream_compliance_chart_ajax,
        name='avg-stream-compliance-chart'),
    url(r'^staff-dashboard/overall-compliance-chart', overall_compliance_chart_ajax,
        name='overall-compliance-chart'),
    url(r'^staff-dashboard/stream-compliance-chart', stream_compliance_chart_ajax,
        name='stream-compliance-chart'),

    # Ajax call for filtering issues on dashboards
    url(r'^dashboard/filter-issues', participant_filter_issues_ajax,
        name='participant_filter_issues'),
    url(r'^staff-dashboard/filter-issues', staff_filter_issues_ajax,
        name='staff_filter_issues'),
    url(r'^staff-dashboard/filter-unassigned-issues', staff_filter__unassigned_issues_ajax,
        name='staff_filter__unassigned_issues'),

    url(r'^issues/', include('tesserae.apps.issue_app.urls', namespace='issues')),
    url(r'^staff-dashboard', StaffDashboardView.as_view(), name='staff_dashboard'),
    url(r'^dashboard', ParticipantDashboardView.as_view(), name='participant_dashboard'),
    url(r'^compliance/', include('tesserae.apps.compliance_app.urls', namespace='compliance')),
    url(r'^payments/', include('tesserae.apps.payment_app.urls', namespace='payments')),
    url(r'^participant/', include('tesserae.apps.participant_app.urls', namespace='participant')),
    url(r'^reports/', include('tesserae.apps.reports_app.urls', namespace='reports')),

    # get average compliance
    url(r'^get-average-compliance', get_average_compliance_data, name='get_average_compliance_data'),

    # get overall compliance
    url(r'^get-overall-compliance', get_overall_compliance, name='get_overall_compliance'),

    # get stream compliance
    url(r'^get-stream-compliance', get_stream_compliance, name='get_stream_compliance'),

]

tesserae/apps/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

tesserae/apps/base_portal/models.py
from django.db import models

# Create your models here.

tesserae/apps/issue_app/models.py
from django.db import models

from tesserae.apps.participant_app.models import Participant
from tesserae.apps.users.models import User
# Create your models here.


# Issue Category model
class IssueCategory(models.Model):
    name = models.CharField(max_length=512)

    def __str__(self):
        return self.name


# Issue Status model
class IssueStatus(models.Model):
    status = models.CharField(max_length=128)
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return self.status


# Contact Method model
class IssueContactMethod(models.Model):
    contact_method = models.CharField(max_length=128)

    def __str__(self):
        return self.contact_method


# Issue model
class Issue(models.Model):
    OPEN = 'Open'
    CLOSED = 'Closed'
    ISSUE_STATUS_CHOICES = (
        (OPEN, 'Open'),
        (CLOSED, 'Closed')
    )
    subject = models.CharField(max_length=1024, blank=False, null=False)
    description = models.TextField(default="", blank=False, null=False)
    reported_by_participant = models.ForeignKey(Participant, related_name='reporting_participant', blank=False, null=False)
    reported_by_user = models.ForeignKey(User, related_name='reporting_user', blank=False, null=False)
    date_reported = models.DateTimeField(auto_now_add=True)
    status = models.ForeignKey('IssueStatus', related_name='issue_status', blank=False, null=False)
    last_updated = models.DateTimeField(auto_now=True)
    category = models.ForeignKey('IssueCategory', related_name='issue_category', blank=False, null=False)
    assigned_to = models.ForeignKey(User, related_name='assigned_admin', limit_choices_to={'is_staff': True},
                                    blank=True, null=True)
    preferred_contact_method = models.ForeignKey('IssueContactMethod', related_name='issue_contact_method', blank=False,
                                                 null=False)

    def __str__(self):
        return '%s - %s' % (self.subject, self.date_reported)

    def get_reportedby_name(self):
        return self.reported_by_participant.participant_id


# Issue Note model - reporting user and admin can add notes to an issue
class IssueNote(models.Model):
    note = models.TextField(default="", blank=True, null=True)
    author = models.ForeignKey(User, related_name="note_author", blank=False, null=False)
    date = models.DateTimeField(auto_now=True)
    issue = models.ForeignKey('Issue', related_name='note_issue', blank=False, null=False)

    def __str__(self):
        return '%i -- %s' % (self.issue.id, self.note)

tesserae/apps/participant_app/forms.py
import re
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from tesserae.apps.participant_app.models import Participant


class NewParticipantForm(forms.ModelForm):
    """
    This form is used for staff members to register new participants
    """

    def __init__(self, *args, **kwargs):
        super(NewParticipantForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_errors = False
        self.helper.add_input(Submit('submit', 'Add Participant', css_class='btn-primary pull-right'))

    participant_id = forms.CharField(label='Participant ID')

    class Meta:
        model = Participant
        fields = [
            'participant_id',
            'gmail'
        ]

    def clean(self):
        print("cleaning...........")
        print(self.cleaned_data)

        error_messages = []

        # validate participant_id
        if Participant.objects.filter(participant_id=self.cleaned_data.get('participant_id')).exists():
            error_messages.append('Participant ID is not unique')
            self._errors["participant_id"] = "Participant with this ID already exists! " \
                                             "Check that Participant ID is entered correctly."

        # validate gmail
        if self.cleaned_data.get('gmail'):
            match = re.search('^(\w+(\.*\w+)*)(@{1})(\w+\.{1}\w+)$', self.cleaned_data.get('gmail'))
            if not match:
                error_messages.append('Gmail must be a valid email address')
                self._errors["gmail"] = "Verify that the email address is entered correctly"

        return self.cleaned_data

tesserae/apps/base_portal/views/adapter.py
"""
ReferebcesL http://django-allauth.readthedocs.io/en/latest/advanced.html?highlight=DefaultAccountAdapter

"""


from django.conf import settings
from allauth.account.adapter import DefaultAccountAdapter

class CustomAccountAdapter(DefaultAccountAdapter):

    # def get_login_redirect_url(self, request):
    #     path = "/accounts/{username}/"
    #     return path.format(username=request.user.username)

    def is_open_for_signup(self, request):
        return True

tesserae/apps/base_portal/views/custom.py
from allauth.account.views import LogoutView
from allauth.socialaccount.models import SocialAccount
from allauth.socialaccount.signals import pre_social_login
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.dispatch import receiver
from django.urls import reverse
from django.views.generic import RedirectView

from tesserae.apps.participant_app.models import Participant
from tesserae.apps.staff_app.models import Staff
from tesserae.apps.users.models import User, UserLogin


class ProfileRedirectView(RedirectView):
    """
    Redirect from 'login' where it takes you to '/accounts/profile/'.
    It redirects to 'root' page or 'next' if any is filled out.
    """
    def get_redirect_url(self, *args, **kwargs):

        print(self.request.user.email)
        url = "#"
        if Participant.objects.filter(gmail=self.request.user.email).exists():
            url = "portal:participant_dashboard"
        if Staff.objects.filter(gmail=self.request.user.email).exists():
            user_obj = User.objects.get(email=self.request.user.email)
            user_obj.is_staff = True
            user_obj.save()
            print("Marked user as staff...")
            url = "portal:staff_dashboard"

        print("===========================")
        print("IN THE PROFILE REDIRECT VIEW")
        print(self.request.user)
        print(url)
        print("===========================")

        # Log the user's login in the database
        user_login = UserLogin.objects.create(user=self.request.user)

        return self.request.GET.get('next', reverse(url))


class CustomLogoutView(LogoutView):
    """
    Custom view that allows changing of the template provided by 'allauth' to use 'our' templates.
    NOTE: View does not add or remove any functionality!
    """
    template_name = "allauth/logout.html"


class CustomEmailLoginView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return "/accounts/google/login/?action=reauthenticate"


@receiver(pre_social_login)
def validate_email_during_login(sender, request, sociallogin, **kwargs):
    """
    This function catches the signal for social login and checks if the email address
    that the user is signing in with is in the participant or staff lists
    """

    # Get the email address of the person attempting to log in
    email_attempting_login = sociallogin.user.email

    if email_attempting_login:
        if Participant.objects.filter(gmail=email_attempting_login).exists():
            print("===========================")
            print("Participant with email " + email_attempting_login + " found!")
            print("===========================")
        elif Staff.objects.filter(gmail=email_attempting_login).exists():
            print("===========================")
            print("Staff with email " + email_attempting_login + " found!")
            print("===========================")
        else:
            print("===========================")
            print("Invalid Email Login Attempt!  " + email_attempting_login)
            print("===========================")
            # Delete social account, social application token, and user
            user_obj = User.objects.filter(email=email_attempting_login)
            SocialAccount.objects.filter(user=user_obj).delete()
            user_obj.delete()
            raise PermissionDenied

tesserae/apps/base_portal/views/landing.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView


class LandingView(TemplateView):
    """
    Template view for the landing page
    """
    template_name = 'landing-page.html'

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_anonymous:
            url = "portal:participant_dashboard"
            if self.request.user.is_staff:
                url = "portal:staff_dashboard"
            return HttpResponseRedirect(reverse(url))
        else:
            context = self.get_context_data(**kwargs)
            return self.render_to_response(context)

tesserae/apps/participant_app/views.py
from allauth.socialaccount.models import SocialAccount
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView
from django import forms

# Create your views here.
from tesserae.apps.participant_app.forms import NewParticipantForm
from tesserae.apps.participant_app.models import Participant
from tesserae.apps.users.models import User


class ParticipantCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    """
    Create View for new Participants
    """
    model = Participant
    template_name = 'participant/create_participant.html'
    form_class = NewParticipantForm
    success_url = reverse_lazy('portal:participant:success_participant_create')

    def __init__(self):
        super(ParticipantCreate, self).__init__()
        self.object = None

    def form_valid(self, form):
        print(self.request.POST)
        self.object = form.save()

        # Create new user object
        new_user_object = User(email=self.request.POST['gmail'], username=self.request.POST['gmail'].split('@')[0])
        new_user_object.save()

        # Create new social account object
        # new_social_acct = SocialAccount(user=new_user_object, provider='Google', uid=)

        return HttpResponseRedirect(self.get_success_url())

    def test_func(self):
        if self.request.user.is_staff:
            return True
        else:
            return False


class ParticipantCreateSuccess(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'participant/success_create_participant.html'

    def get_context_data(self, **kwargs):
        context = super(ParticipantCreateSuccess, self).get_context_data(**kwargs)

        return context

    def test_func(self):
        return self.request.user.is_staff

tesserae/apps/staff_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from tesserae.apps.staff_app.forms import StaffForm
from tesserae.apps.staff_app.models import Staff


class StaffCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    """
    Create View for new Issues
    """
    model = Staff
    template_name = 'staff/create_staff.html'
    form_class = StaffForm
    success_url = reverse_lazy('portal:staff_dashboard')

    def __init__(self):
        super(StaffCreate, self).__init__()
        self.object = None

    def form_valid(self, form):
        print(self.request.POST)
        self.object = form.save(commit=True)

        return HttpResponseRedirect(self.get_success_url())

    def test_func(self):
        if self.request.user.is_staff and self.request.user.is_superuser:
            return True
        else:
            return False

tesserae/templates/issues/create_issue.html
{% extends 'gentelella-portal-base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}Create Issue{% endblock title %}

{% block content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left" style="width: 100%;">
                    <h3>Report a New Issue  <small style="font-size: 14px; float: right;"><a style="text-decoration: underline;" href="https://drive.google.com/a/nd.edu/file/d/1tTHlxCoOtgW_K1orN8FrXq899ziE_fzc/view?usp=sharing" target="_blank">Frequenty Asked Questions</a></small></h3>
                </div>
            </div>
            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>New Issue</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <form action="" method="post" novalidate>{% csrf_token %}
                                {% if form.errors %}
                                    <div class="well form-error-well">
                                        <strong>Please correct the following errors:</strong>
                                        <br/>
                                        <br/>
                                        {{ form.non_field_errors }}
                                        <ul class="errorlist">
                                            {% for key,value in form.errors.items %}
                                                <li><strong>{{ key }}</strong> {{ value }}</li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                {% endif %}
                                {% crispy form %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
  <div class="modal fade" id="faq_modal" role="dialog">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header bg-primary">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Issues - Frequently Asked Questions / Issue Resolution</h4>
        </div>
        <div class="modal-body">
          <p> Before submitting an issue, we encourage you to check our FAQ document at the <a style="text-decoration: underline;" href="https://drive.google.com/a/nd.edu/file/d/1tTHlxCoOtgW_K1orN8FrXq899ziE_fzc/view?usp=sharing" target="_blank">Google Doc FAQ</a>.<br />
    If you do not find your answer, please submit your issue.
          </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block js %}
<script>
    $(document).ready(function(){
       $('#faq_modal').modal();
    });
</script>
{% endblock %}

tesserae/templates/issues/issue_detail_note_list.html
<!-- begin of issue notes -->
<ul class="messages">
    {% if note_list %}
        {% for item in note_list %}
            <li id="note_list_item">
                <div class="message_date" data-toggle="tooltip"
                     data-placement="left" title="{{ item.date }}">
                    <h3 class="date text-info">{{ item.date.date.day }}</h3>
                    <h4 class="month">{{ item.date|date:"F" }}</h4>
                </div>
                <div class="message_wrapper">
                    <h4 class="heading">{{ item.author.name }}</h4>
                    <blockquote class="message">
                        {{ item.note }}
                    </blockquote>
                    <br/>
                    <br/>
                </div>
            </li>
        {% endfor %}
    {% else %}
        <h4 class="text-center" style="padding-top:25px">No Notes Yet</h4>
    {% endif %}
</ul>
<!-- end of issue notes -->

tesserae/templates/issues/view_issues_list.html
{% extends 'gentelella-portal-base.html' %}
{% load static %}

{% block extra_css %}
    <!-- Datatables -->
    <link href="{% static 'bower_components/gentelella/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bower_components/gentelella/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bower_components/gentelella/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bower_components/gentelella/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bower_components/gentelella/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css' %}" rel="stylesheet">
{% endblock extra_css %}

{% block title %}Issues{% endblock title %}

{% block content %}
    <!-- page content -->
    <div class="right_col" role="main">
{#        <div class="">#}
            <div class="page-title">
                <div class="title_left">
                    <h3>Issues</h3>
                </div>
            </div>


            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>
                                {% if request.user.is_staff %}
                                    Issues List
                                {% else %}
                                    My Issues
                                {% endif %}
                            </h2>
                            <div class="clearfix"></div>
                        </div>

                        <div class="x_content">
                            <div><p></p></div>
                            <div class="table-responsive">
                                 <table id="issue-table" class="table table-bordered table-hover">
                                    <thead>
                                    <tr class="headings">
                                        <th class="column-title">Issue #</th>
                                        <th class="column-title">Status</th>
                                        <th class="column-title">Category</th>
                                        <th class="column-title">Subject</th>
                                        <th class="column-title">Date Reported</th>
                                        {% if request.user.is_staff %}
                                            <th class="column-title" id="assignedToColumn">Assigned To</th>
                                        {% endif %}
                                        <th class="column-title">Last Updated</th>
                                        <th class="column-title"></th>
                                        <th class="hidden">Participant ID</th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    {% for issue in issue_list %}
                                        <tr>
                                            <td class=" ">{{ issue.id }}</td>
                                            <td class=" ">{{ issue.status }}</td>
                                            <td class=" ">{{ issue.category }}</td>
                                            <td class=" ">{{ issue.subject }}</td>
                                            <td class=" " data-order='{{ issue.date_reported|date:"U" }}'>{{ issue.date_reported }}</td>
                                            {% if request.user.is_staff %}
                                                <td class=" ">
                                                    {% if issue.assigned_to %}
                                                        {{ issue.assigned_to }}
                                                    {% else %}
                                                        -
                                                    {% endif %}
                                                </td>
                                            {% endif %}
                                            <td class=" " data-order='{{ issue.last_updated|date:"U" }}'>{{ issue.last_updated }}</td>
                                            <td class="center-block">
                                                <a class="btn btn-primary btn-xs"
                                                   href="{% url 'portal:issues:issue_details' pk=issue.id %}">
                                                    Details
                                                </a>
                                                {% if request.user.is_staff %}
                                                    <a class="btn btn-xs btn-warning"
                                                       href="{% url 'portal:issues:admin_issues_update' pk=issue.id %}">
                                                        Update
                                                    </a>
                                                {% endif %}
                                            </td>
                                            <td class="hidden">{{ issue.reported_by_participant }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
{#        </div>#}
    </div>
{% endblock content %}

{% block js %}
    <!-- Datatables -->
    <script src="{% static 'bower_components/gentelella/vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/jszip/dist/jszip.min.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/pdfmake/build/pdfmake.min.js' %}"></script>
    <script src="{% static 'bower_components/gentelella/vendors/pdfmake/build/vfs_fonts.js' %}"></script>

        <script type="text/javascript">
        $(document).ready(function () {
            initIssueTable();
        });

        function initIssueTable() {
            /* DATA TABLES  for Issues */

            if (typeof ($.fn.DataTable) === 'undefined') {
                return;
            }
            console.log('init_IssueTable');
            var lastColumnIndex = 7;
            if( $('#assignedToColumn').index()<0){
             lastColumnIndex = 6;
            }

            console.log(lastColumnIndex);
            $('#issue-table').dataTable({
              "aoColumnDefs": [
                  { 'bSortable': false, 'aTargets': [ lastColumnIndex ] }
               ]
            }); // Turn off search box


        }

    </script>

{% endblock js %}